version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
    networks:
      - bot-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=skillbox
      - POSTGRES_USER=skillbox
      - POSTGRES_PASSWORD=skillbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillbox -d skillbox"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge